# Generated by Django 5.2 on 2025-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.TextField()),
                ('course_id', models.TextField()),
                ('user_id', models.IntegerField()),
                ('certificates', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
