# Generated by Django 5.2 on 2025-04-10 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_app', '0002_course_alter_profile_certificates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.TextField(default='TODO'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tool_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
