# Generated by Django 5.2 on 2025-04-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_app', '0003_remove_course_certificates_remove_course_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.TextField(default='Not Started'),
        ),
    ]
