# Generated by Django 5.2 on 2025-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_app', '0004_alter_course_end_time_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
