airflow_operators:
  - PythonOperator
  - BashOperator
  - DummyOperator
  - EmailOperator
  - SimpleHttpOperator
  - ExternalTaskSensor
  - FileSensor
  - HdfsSensor
  - S3KeySensor
  - HttpSensor
  - DockerOperator
  - KubernetesPodOperator
  - SlackAPIPostOperator
  - DiscordWebhookOperator
  - BranchPythonOperator
  - SubDagOperator
  - SparkSubmitOperator
  - DataflowPythonOperator
  - BigQueryOperator
  - PythonVirtualenvOperator
  - PostgresOperator
  - MySqlOperator
  - SQLiteOperator
  - MSSQLOperator
  - SFTPOperator
  - FTPOperator
  - HiveOperator
  - GCSToBigQueryOperator
  - BigQueryToGCSOperator
  - EmrCreateJobFlowOperator
  - LambdaInvokeFunctionOperator
  - DynamoDBToS3Operator
  - AthenaOperator
  - DataflowOperator
  - DataprocSubmitJobOperator
  - CloudFunctionInvokeOperator
  - AzureDataFactoryRunPipelineOperator
  - WasbCreateBlobOperator
